### ISSUE TITLE
Paths break when coordinates are very small (scientific notation not parsing)

### ISSUE THREAD

**Issue by mejmt** [mhemesath/r2d3#101]
This is a common problem when using D3 generate splines that end up having a point very near 0.

For example, this SVG:

&lt;path ... d="M144.18593347497045,0L4.4144210478048946e-15,72.09296673748523L-144.18593347497045,1.7657684191219578e-14"&gt;

incorrectly converts to this VML:

&lt;rvml:shape ... coordsize = "21600,21600" ... path = " m3114416,0 l-324000,1557208,-3114416,0,-302400,0 e"&gt;

Notice that the output has 4 points instead of 3. If you do the coordsize conversion on the VML points, it's clear that it's failing to parse the scientific notation (XXXe-15, XXXe-14).

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
