### ISSUE TITLE
exception thrown and not caught error on IE8

### ISSUE THREAD

**Issue by hsuh** [mhemesath/r2d3#107]
on Line 6329
Wrapping the line try{}catch{} seems to have solved the problem. 

try {
        if (l === 0) throw new TypeError("Array length is 0 and no second argument");
     }  
 catch(err){
 //do nothing
   }

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
