### ISSUE TITLE
d3.transform re-creates paper

### ISSUE THREAD

**Issue by cvwillegen** [mhemesath/r2d3#111]
The d3.transform function does the following:

```
var paper = Raphael(document.body, 0, 0);
```

However, there (probably) already is a paper object. Now, a new div is created and inserted before the first child in the document,body, resulting in the display of an empty block on-screen.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
