### ISSUE TITLE
Modifying tick size with .tickSize() causes axis to be painted black.

### ISSUE THREAD

**Issue by blakedietz** [mhemesath/r2d3#112]
var yAxis = d3.svg.axis().scale(yScale)
.orient("left")
.ticks(4);
// Force the ticks to have a width that extends across the axis to the right side of the graph
.tickSize(-width); 

![screen shot 2013-07-25 at 10 21 15 am](https://f.cloud.github.com/assets/2549228/857577/593056f6-f554-11e2-8972-7a4756f61691.png)

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
