### ISSUE TITLE
rotate not backward compatible

### ISSUE THREAD

**Issue by r2d3user** [mhemesath/r2d3#119]
Hi,

Recently I upgraded to version 0.2.0 and noticed that the code for setting the Y axis label no longer works:

``` javascript
 svg.append('text')
                  .attr('class', 'axis-label y')
                  .attr('text-anchor', 'middle')
                  .attr('x', myX)
                  .attr('y',myY)
                  .attr('transform', 'rotate(-90)')
                  .attr("font-size", 14)
                  .text('my y label');
```

I think this may have worked if I removed the x and y attrs and used a translate in  the transform. But shouldn't the library be backward compatible?

Likewise, the following code to rotate the x-axis tick labels had an odd behavior. When the page loads, the tick labels are properly aligned., But as soon as I redraw the graph (because data changes dynamically), the x axis tick tables go above the x axis

``` javascript
.attr("transform", function(d) {
                        // slightly slant the tick labels to avoid overlapping when they are too close by
                       return "translate(" + (focusAreaProperties.padding.left + d3.mean(metaGroups[2][d])) + "," +
                               (focusAreaProperties.y2 + (focusAreaProperties.offset.y * 2)) + ")rotate(45)"
```

Again, the problem is solved if I continue to use the older version. Unfortunately, I cannot tell you what the older version is because some other developer has added that file

It would be much appreciated if you could take a look.

Regards,
John

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
