### ISSUE TITLE
'this.raphaelNode' is null or not an object (line 10636)

### ISSUE THREAD

**Issue by ldub** [mhemesath/r2d3#122]
In ie8, when I try to use .attr() in order to modify an attribute, I get this error (but not always, i think).

my code:

```
 d3.select(selector).select('svg').remove();
    svg = d3.select(selector)
        .append('svg')
        .attr("id", "main-svg")
        .attr('width', config.width)
        .attr('height', config.height);

    if (config.zoomable) {
        zoom = d3.behavior.zoom()
            .scale(1)
            .translate([0,0])
            .on('zoom', redraw);
        svg = svg.append('g')
            .attr('class', 'zoomable')
            .attr('width', 500) //THIS LINE IS IN ERROR CALLSTACK
            .attr('height', 500)
            .call(zoom)
            .attr('transform', 'translate(' + (-config.width/2) + ',' + (-config.height/2) + ') scale(2)')
            .append('g');

        svg.append('rect')
            .attr('width', config.width)
            .attr('height', config.height)
            .attr('fill', 'white');
    }
```

The exception is thrown on this line of code in r2d3:

```
  case "width":
   var width = this.domNode.getAttribute("width") || 0, height = this.domNode.getAttribute("height") || 0;
   if (this.domNode.tagName === "svg") {
     this.paper.setSize(width, height);
   } else {
     this.raphaelNode.attr("width", width); //THIS LINE CAUSES ERROR
   }
   break;
```

Unfortunately, this is part of a large project and I can't seem to create an isolated jsfiddle that demonstrates the issue :/
I'd appreciate any help, and let me know if there is anything I can do.

**Comment by xiaohan2013** [comment]
I am encountering the same problem , but using .attr() methods for updating element's href attribute 

     case "href":
-->  this.raphaelNode.attr("src", this.domNode.getAttribute("href"));
      break;

'this.raphaelNode' is null or not an object 

About updating element''s attribute of href , is there better solution for fixing this?

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
