### ISSUE TITLE
Transform requires additional attributes

### ISSUE THREAD

**Issue by IPWright83** [mhemesath/r2d3#125]
I noticed the yesterday a slight issue when trying to do a translation transform similar to the following:

```
.attr("transform", function (d) { return "translate(" + d.x + ")"; });
```

The translation just got completely ignored. I managed to track this down to the fact that two parameters are expected when using R2D3, so the following fixed it:

```
.attr("transform", function (d) { return "translate(" + d.x + ", 0)"; });
```

A minor issue but should be quite easy to fix.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
