### ISSUE TITLE
Line stroke CSS not working in IE8

### ISSUE THREAD

**Issue by NageshChawan** [mhemesath/r2d3#126]
I have implemented a boxplot using R2D3 to support IE8. I am not able to set the line stroke to the plot.

IE8:

![image](https://f.cloud.github.com/assets/5089235/1066359/186edb16-13b2-11e3-854a-810592fa4cc5.png)

Other Browsers:

![image](https://f.cloud.github.com/assets/5089235/1066365/46fe7784-13b2-11e3-902a-b32863dd8e18.png)

Following is snippet of code for one of the whisker lines:

```
 var g = d3.select(this)
 var whisker = g.selectAll("line.whisker")
      .data(whiskerData || []);

   whisker.enter().insert("line")
      .attr("class", "whisker")
      .attr("x1", 0)
      .attr("y1", x1) // x1 is the scale
      .attr("x2", width)
      .attr("y2", x1);
```

CSS:

```
.box line { // box is also a class for the svg.
fill: #fff;
stroke: #000;
stroke-width: 1.5px;
  }
```

Why am i not able to see line strokes in IE8. Please Help.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
