### ISSUE TITLE
Transform attribute giving error in IE8

### ISSUE THREAD

**Issue by NageshChawan** [mhemesath/r2d3#127]
I am trying to render a force layout using R2D3 in IE 8.

```
node.attr("transform", function(d) {
                return "translate(" + d.x + "," + d.y + ")";
            });
```

Inside the force tick() method when I call transform for the node I get this error:Arg: Illegal input string in Vector2D at line 4793 skew.offset = matrix.offset() in the r2d3.js. Problem what I see here is IE8 browser engine is not able to read the large numbers which are returned by this translate method. I am not able to understand how are this large numbers returned by the translate method which should ideally return each nodes x and y position.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
