### ISSUE TITLE
IE8 Permission denied when trying to perform AJAX request

### ISSUE THREAD

**Issue by monsieurBelbo** [mhemesath/r2d3#131]
When making an AJAX request through `d3.json()` to an external resource (hosted on another domain) on IE8 (Windows 7) I get:

```
Permission denied
r2d3.js                        Line: 7125
```

Which is the call to `request.open()`.
Note: I'm using the development version of r2d3.js

The error doesn't occur if I use `d3.json()` on a local resource.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
