### ISSUE TITLE
How to get Raphael canvas after r2d3 has finished drawing?

### ISSUE THREAD

**Issue by slavik112211** [mhemesath/r2d3#132]
Hi,

got a question regarding the usage of r2d3.

After r2d3 has finished converting d3 code into raphael code and that has been converted into VML (if in IE8), is there a way to retrieve raphael canvas, so that further modifications to the graphics object can be done directly with Raphael?

The problem is that to do any modifications on the object, Raphael requires a link to the canvas ("paper", or simply Raphael object), and it seems that this object cannot be retrieved from DOM:

var paper = Raphael('paper', 640, 200);
var circle = paper.circle(100, 100, 80).attr({fill: Raphael.getColor()});

Thanks,
Slavik

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
