### ISSUE TITLE
r2d3.js crashes IE8 when running in XP

### ISSUE THREAD

**Issue by DavidHughes** [mhemesath/r2d3#133]
I'm not sure how high this is on your list of priorities but I noticed at work that this script causes IE8 to crash on page load when running on Windows XP.

I've confirmed that it is indeed this script by making a quick html page that only includes r2d3, IE8 crashed when I opened this page.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
