### ISSUE TITLE
Is using d3.svg.brush() supported?

### ISSUE THREAD

**Issue by ghost** [mhemesath/r2d3#134]
I'm add r2d3 adapter code to this example (http://bl.ocks.org/mbostock/1667367), but that has black block in IE8. I think it's  d3.svg.brush() problem, is right?  has any way to      solve it?

```
<!--[if lte IE 8]><script src="r2d3.js" charset="utf-8"></script><![endif]-->
<!--[if gte IE 9]><!-->
<script src="http://d3js.org/d3.v3.min.js"></script>
<!--<![endif]-->
```

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
