### ISSUE TITLE
Does xlink:href work on 'a tag'?

### ISSUE THREAD

**Issue by hdahm** [mhemesath/r2d3#137]
I can add an 'a tag' to the rectangle element and I can add a link to plain text using r2d3 but for some reason I cannot get it to add a link to the 'a tag'.

I created a html file so that someone could download it and test it in ie8. https://dl.dropboxusercontent.com/u/23726217/test.html

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
