### ISSUE TITLE
request for scaling on window resize example

### ISSUE THREAD

**Issue by gmculp** [mhemesath/r2d3#142]
Here is an example of scaling a circle based on window resize in D3 using the viewbox attribute:
http://christopheviau.com/d3_tutorial/d3_examples/

How can this be accomplished using r2d3?

Thank you.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
