### ISSUE TITLE
Upgrade R2D3 to D3 v3.4.6

### ISSUE THREAD

**Issue by webmaven** [mhemesath/r2d3#146]
I came across a D3 feature that I was trying to use that was added in D3 v3.1 (ie. one release later than the one R2D3 uses). Specifically, `d3.csv.parse` now takes an accesor function as an optional 2nd parameter: https://github.com/mbostock/d3/wiki/CSV#parse

There have been many other features and bugfixes added to D3 since v3.0.8: https://github.com/mbostock/d3/releases

So, please upgrade the version of D3 that R2D3 is based on. Latest version would be best, but any later version would still be a help.

**Comment by LorenzGardner** [comment]
Needs a 3.5.x update now.

As this is a year old, am I correct in assuming R3D3 does not intend to support D3 versions past v3.0.8 anytime soon / ever?

**Comment by gneatgeek** [comment]
I don't think it's likely without it being a contribution, but @mhemesath could probably give a more definitive opinion.  I will say that I've successfully been able to run R2D3 alongside D3 v3.3.6. That said, I may not be using a feature(s) that you are.

**Comment by webmaven** [comment]
Closing due to death of project. :skull:
