### ISSUE TITLE
in ie8 issue with this.style undefined

### ISSUE THREAD

**Issue by LorenzGardner** [mhemesath/r2d3#147]
I'm using dc.js (that uses d3.js and crossfitler.js) and I'm trying to use r2d3 to provide ie8 compatibility but ran into an issue.

Line 8932 of r2d3.js reads
<code>
if (this.style.setProperty)
</code>

this.style is undefined and thus this causes problems. Looking at this in the ie8 watch window I can see the this object is not a dom object, but this.domNode is defined.

before line 8932 i simply added a check to see if this.style was undefined and if so use this.domNode.style instead. That seemed to solve all my issues.

I do note there are 4 places in r2d3.js where this.style.setProperty is used and not sure if they would all need to be addressed.

I admit I don't understand what the code is doing or what is going on and this is just a blind hack that happens to be working for me currently. Probably not the "right thing" to do. But Just thought I'd report the issue I'm seeing in case some one with more knowledge of r2d3 / d3  gets a chance to look at it.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
