### ISSUE TITLE
R2D3 is not supporting D3 Guage graphs

### ISSUE THREAD

**Issue by ksudarson18** [mhemesath/r2d3#149]
Hi,
 i implemented d3 guage graph using r2d3 but the styles are not displaying properly in page it tried to include various styles like shim,raphael,sizzle but nothing works please help me out..

Thanks in advance...

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
