### ISSUE TITLE
D3 Multi-resolution time format missing

### ISSUE THREAD

**Issue by neilwightman** [mhemesath/r2d3#152]
Both 

```
  d3.time.format.multi
  d3.time.format.utc.multi
```

are missing in r2d3.  See :
https://github.com/mbostock/d3/wiki/Time-Formatting#format_multi

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
