### ISSUE TITLE
Invalid Argument in IE8 when appending 'tr' tag

### ISSUE THREAD

**Issue by ChibiTomo** [mhemesath/r2d3#153]
I have an application that uses D3.js, but I have to make it compatible with IE8... So I used R2D3.js, which seems to be a really good alternative for SVG manipulation. But for basic tags...

I use it to manage data inside a table, but when it comes to append a new row, IE says:

> Line: 8450 
> Error: Invalid argument.

Here is a simple example: 

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!--[if lte IE 8]><script src="r2d3.js" charset="utf-8"></script><![endif]-->
        <!--[if gte IE 9]><!-->
        <script src="d3.min.js" charset="utf-8"></script>
        <!--<![endif]-->
    </head>

    <body>
        <table>
        </table>

        <script>
var dataset = [
    {
        name: 'Foo',
        age: 42
    },  
    {
        name: 'Bar',
        age: 21
    }
];

var table = d3.select('table');
table.selectAll('tr').data(dataset)
    .enter().append('tr')
    .selectAll('td')
        .data(function(d) {
            return [d.name, d.age];
        })
        .enter().append('td')
            .text(function(d) {return d});
        </script>
    </body>
<html>
```

This works perfectly with Firefox, but crashes on IE8.

Here is a [JSFiddle](http://jsfiddle.net/bw9c5b0r/1/).

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
