### ISSUE TITLE
IE8: Object doesn't support property or method 'removeAttributeNS'

### ISSUE THREAD

**Issue by vanquang9387** [mhemesath/r2d3#154]
I get this error on IE8:

```
SCRIPT438: Object doesn't support property or method 'removeAttributeNS'
File: r2d3.js, Line: 8254, Column: 22
```

Method 'removeAttributeNS' is supported from IE9:
https://msdn.microsoft.com/en-us/library/ff975203%28v=vs.85%29.aspx

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
