### ISSUE TITLE
Drag Events

### ISSUE THREAD

**Issue by IPWright83** [mhemesath/r2d3#20]
I've been unable to get drag events working with the original D3 syntax. Ultimately this will rely on a transformation (I know these aren't working) but the event seems to fail well before this.

```
function d3_mousePoint(container, e) {
   var svg = container.ownerSVGElement || container;
```

I get an exception "Unable to read ownerSVGElement of undefined". 

I believe I've correctly removed all my groups (and am now using 'set' instead to verify that it wasn't the unmerged trunk code causing issues). A small sample of code that should help to reproduce is as follows. If I un-comment the click event then that works correctly. I've not included the dragMove function because it doesn't get anywhere near that far.

```
var sankey = d3.sankey()
  .nodeWidth(15)
  .nodePadding(10)
  .size([width, height]);

  d3.json("energy.json", function(energy) {
    ...
    ...
    sankey
     .nodes(energy.nodes)
     .links(energy.links)
     .layout(32);

    var node = svg.append("set").selectAll(".node")
     .data(energy.nodes)
     .enter().append("set")
     .attr("class", "node");

    node.append("rect")
     .attr("height", function(d) { return d.dy; })
     .attr("width", sankey.nodeWidth())
     .attr("fill", function(d) { return d.color = color(d.name.replace(/ .*/, "")); })
     .attr("stroke", function(d) { return d3.rgb(d.color).darker(2); })
     .attr("transform", function(d) { return "t" + d.x + "," + d.y + ""; })
      //.on('click', function() { alert('clickTest'); })
      .call(d3.behavior.drag()
        .origin(function(d) { return d; })
        .on("dragstart", function() { this.parentNode.appendChild(this); })
        .on("drag", dragmove));
```

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
