### ISSUE TITLE
Support for Append("title")

### ISSUE THREAD

**Issue by IPWright83** [mhemesath/r2d3#21]
I believe Raphael doesn't support "title" but instead uses "text". Therefore calls such as the following will fail:

```
node.append("title")
  .text(function(d) { return d.name + "\n" + format(d.value); })
```

Simple workaround is to replace "title" with "text", but it's an inconsistency with D3.

```
node.append("text")
  .text(function(d) { return d.name + "\n" + format(d.value); })
```

I should add that the error is "Property 'title' of object #<R> is not a function" within Raphael.fn.appendChild.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
