### ISSUE TITLE
Unable to use r2d3 in an AMD-enabled project because of raphael.js and sizzle.

### ISSUE THREAD

**Issue by cronco** [mhemesath/r2d3#48]
The problem is actually in [raphael.js](https://github.com/DmitryBaranovskiy/raphael/blob/master/raphael.js#L222). If define exists, eve is undefined for Raphael and initialization fails.

I made it temporarily work by removing the `typeof define != 'undefined'` clause from the line above in my build of r2d3, but a more elegant solution isn't far.

(The same applies to sizzle)

An AMD-ready version of r2d3 should be made available.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
