### ISSUE TITLE
Support <use> Element

### ISSUE THREAD

**Issue by michaelsbradleyjr** [mhemesath/r2d3#49]
I attempted to use `r2d3` to get something like this [Curved textPath](http://bl.ocks.org/2565344) demo working in IE 8 (linked to the original demo, not my adaptation).

However, pre-9 versions of IE are complaining that `Object doesn't support property or method 'setAttributeNS'`.

Is this a known issue? Any known workarounds?

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
