### ISSUE TITLE
Can't append text to paper that is appended to <p> in IE8

### ISSUE THREAD

**Issue by neight-allen** [mhemesath/r2d3#66]
HTML:

``` html
<p id="paper"></p>
```

javascript:

``` javascript
var svg = 
    d3.select("#paper").append("svg")
        .attr({
            width: "200",
            height: "200"
        });
svg.append("text")
    .attr({
        x: "100",
        y: "100"
    })
    .text("hi");
```

And I'm getting the following error in IE8:

```
Unknown runtime error r2d3.v2.js line 5178
```

This works just fine in chrome, and it works if you change the `<p>` to a `<div>`.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
