### ISSUE TITLE
addEventListener IE8-Fix

### ISSUE THREAD

**Issue by janein** [mhemesath/r2d3#79]
Hi!
I had a problem to get it working on IE8.
Log said "no method AddEventListener".
So i changed this line (10000):

this.addEventListener(type, this[name] = wrapper, wrapper.$ = capture);

to:

if (!this.addEventListener) {
        this.attachEvent(type, this[name] = wrapper, wrapper.$ = capture);
    }
    else {
        this.addEventListener(type, this[name] = wrapper, wrapper.$ = capture);
    }

Hope it helps!

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
