### ISSUE TITLE
d3.mouse() doesn't work in IE8

### ISSUE THREAD

**Issue by yl013512** [mhemesath/r2d3#82]
In IE8, I am trying to use d3.mouse(this) to allocate the coordinates then apply them to a tooltip div .offset(). The tooltip div doesn't move around as the mouse moving around.  The following is the code: 

 mouseover = function (d, i) {
     var coords = d3.mouse(this);
    var x = coords[0];  
    var y = coords[1]; 
    $pie_chart_tooltip.offset({ left: x, top: y });  
    $pie_chart_tooltip.css({ 'visibility':'visible'});
}

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
