### ISSUE TITLE
Support for dx, dy attributes for text elements

### ISSUE THREAD

**Issue by sun16** [mhemesath/r2d3#88]
I had a use case for centering text in an SVG element. After investigating, I found that Raphael's behavior for `attr('text-anchor', 'middle')` is to center the text directly in the middle of element (which is what I wanted anyways), while in SVG the behavior is to display the text above the middle line so that you have to use the dy attr to push the text down.

http://jsfiddle.net/dj99u/

However maybe someone else might have a use for dx/dy on text elements, but you'll have to keep in mind the discrepancy between Raphael and SVG implementation of the text-anchor attribute. This is not an issue/priority for me and can be closed, just a heads up for anyone who's wondering about dx/dy support.

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
