### ISSUE TITLE
Support for translate

### ISSUE THREAD

**Issue by hugovicard** [mhemesath/r2d3#96]
Hello

I attempted to use r2d3 to get a dynamic pie chart or radar chart, i found an example of one on jsfiddle : http://jsfiddle.net/MX7JC/9/

When i test it on IE8 with R2D3, the pie chart execute a vertical translation of the entire chart, how to get a fix pie whith only text translation ?

thx for your help

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
