### ISSUE TITLE
Support for linear and radial gradients

### ISSUE THREAD

**Issue by sun16** [mhemesath/r2d3#97]
Example:
http://jsfiddle.net/GVfpT/

The generated SVG from the example:
http://jsfiddle.net/hXfgH/

References:
http://www.w3schools.com/svg/svg_grad_linear.asp
http://www.w3.org/TR/SVG/pservers.html
http://raphaeljs.com/reference.html#Element.attr

**Comment by roryhardy** [comment]
Hi there,

This project is no longer being maintained so this issue is being closed. Thank you for using r2d3 and taking the time to report this issue.
